=== Jasperrr91/TeamRobot/json_schema/teamrobot_json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "structure": {
      "type": "object",
      "properties": {
        "prepositional_phrases_count": {
          "type": "integer"
        },
        "adjective_count": {
          "type": "integer"
        },
        "non_future": {
          "type": "integer"
        },
        "active_sentences": {
          "type": "integer"
        },
        "personal_pronouns": {
          "type": "integer"
        },
        "word_length": {
          "type": "number"
        },
        "negations": {
          "type": "integer"
        },
        "adverbs": {
          "type": "integer"
        },
        "passive_sentences": {
          "type": "integer"
        },
        "number_of_sentences": {
          "type": "integer"
        },
        "future": {
          "type": "integer"
        },
        "wordcount": {
          "type": "integer"
        }
      },
      "required": [
        "prepositional_phrases_count",
        "adjective_count",
        "non_future",
        "active_sentences",
        "personal_pronouns",
        "word_length",
        "negations",
        "adverbs",
        "passive_sentences",
        "number_of_sentences",
        "future",
        "wordcount"
      ]
    },
    "metadata": {
      "type": "object",
      "properties": {
        "speaker": {
          "type": "string"
        },
        "lang": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "input_text": {
          "type": "string"
        },
        "people_present": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "script_id": {
          "type": "string"
        },
        "location": {
          "type": "object",
          "properties": {
            "geometry": {
              "type": "object",
              "properties": {
                "coordinates": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  }
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "coordinates",
                "type"
              ]
            },
            "type": {
              "type": "string"
            },
            "properties": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "required": [
            "geometry",
            "type",
            "properties"
          ]
        },
        "scene_id": {
          "type": "string"
        }
      },
      "required": [
        "speaker",
        "lang",
        "timestamp",
        "input_text",
        "people_present",
        "script_id",
        "location",
        "scene_id"
      ]
    },
    "semantic": {
      "type": "object",
      "properties": {
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "organisations": {
          "type": "array",
          "items": {}
        },
        "people": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "places": {
          "type": "array",
          "items": {}
        },
        "topics": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "keywords",
        "organisations",
        "people",
        "places",
        "topics"
      ]
    },
    "emotions": {
      "type": "object",
      "properties": {
        "detected_emotion": {
          "type": "array",
          "items": {}
        },
        "information_state": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "detected_emotion",
        "information_state"
      ]
    }
  },
  "required": [
    "structure",
    "metadata",
    "semantic",
    "emotions"
  ]
}

=== Jasperrr91/TeamRobot/sample_input.json
{"semantic": {"places": [], "keywords": ["televisie", "goedendag"], "people": ["jelle", "Richard Franzen"], "topics": ["introduction"], "organisations": []}, "emotions": {"detected_emotion": [], "information_state": []}, "metadata": {"people_present": ["Richard", "Jelle"], "script_id": "episode_1", "timestamp": "2016-11-18T08:35:44.566050", "lang": "nl", "scene_id": "scene_1", "location": {"geometry": {"coordinates": [35.41, 139.41], "type": "Point"}, "type": "Feature", "properties": {"name": "Tokyo, Japan"}}, "input_text": "We are looking for Richard Franzen, an American who has built a robot, he resides in Tagoyashi.", "speaker": "Jelle"}, "structure": {"adverbs": 0, "personal_pronouns": 2, "passive_sentences": 0, "active_sentences": 2, "future": 0, "word_length": 6.09, "adjective_count": 1, "non_future": 2, "negations": 0, "prepositional_phrases_count": 1, "number_of_sentences": 1, "wordcount": 11}}

=== Jasperrr91/TeamRobot/untitled folder/sample_input.json
{"emotions": {"detected_emotion": [], "information_state": []}, "structure": {"active_sentences": 2, "future": 0, "wordcount": 11, "prepositional_phrases_count": 1, "word_length": 6.09, "adverbs": 0, "passive_sentences": 0, "non_future": 2, "adjective_count": 1, "negations": 0, "personal_pronouns": 2, "number_of_sentences": 1}, "semantic": {"keywords": ["televisie", "goedendag"], "topics": ["introduction"], "people": ["jelle", "Richard Franzen"], "organisations": [], "places": ["Tagoyashi"]}, "metadata": {"speaker": "Jelle", "scene_id": "scene_1", "people_present": ["Richard", "Jelle"], "input_text": "We are looking for Richard Franzen an American who has built a robot. He resides in Tagoyashi.", "timestamp": "2016-11-18T08:35:44.566050", "script_id": "episode_1", "location": {"type": "Feature", "geometry": {"type": "Point", "coordinates": [35.41, 139.41]}, "properties": {"name": "Tokyo, Japan"}}, "lang": "nl"}}

=== Jasperrr91/TeamRobot/untitled folder/input_2.json
{
  "structure": {
    "prepositional_phrases_count": 1,
    "adjective_count": 1,
    "non_future": 2,
    "active_sentences": 2,
    "personal_pronouns": 2,
    "word_length": 6.09,
    "negations": 0,
    "adverbs": 0,
    "passive_sentences": 0,
    "number_of_sentences": 1,
    "future": 0,
    "wordcount": 11
  },
  "metadata": {
    "speaker": "Jelle",
    "lang": "nl",
    "timestamp": "2016-11-18T08:35:44.566050",
    "input_text": "Goedendag, ik ben van de Nederlandse televisie. Mijn naam is Jelle.",
    "people_present": [
      "Richard",
      "Jelle"
    ],
    "script_id": "episode_1",
    "location": {
      "geometry": {
        "coordinates": [
          35.41,
          139.41
        ],
        "type": "Point"
      },
      "type": "Feature",
      "properties": {
        "name": "Tokyo, Japan"
      }
    },
    "scene_id": "scene_1"
  },
  "semantic": {
    "keywords": [
      "televisie",
      "goedendag"
    ],
    "organisations": [],
    "people": [
      "jelle"
    ],
    "places": [],
    "topics": [
      "introduction"
    ]
  },
  "emotions": {
    "detected_emotion": [],
    "information_state": []
  }
}
